# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05550f4e1a63d21bcaa0da2e6046430dd2d19d1ebf77e512d3625477ae3b0e4ca5fa27d0e445d0c41319f642b141ba798d16a3741bf836c92a237d64afd5d02c

test:
  secret_key_base: 473e1142bd4e675c358f9326a13b9b9d9d078bd096283d4d7c176921fcd910dd1613b7b5de491da6a2ba6bf4c84ad14b84b410aa4314949bc0f9184c9f70c49e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
